---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axonserver
  labels:
    app: axonserver
  namespace: dev
spec:
  serviceName: axonserver
  replicas: 1
  selector:
    matchLabels:
      app: axonserver
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
      - name: axonserver
        image: axoniq/axonserver:latest-jdk-17-dev
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 8124
          protocol: TCP
        - name: gui
          containerPort: 8024
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8024
            path: /actuator/health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        env:
          - name: axoniq.axonserver.standalone
            value: "true"
          - name: axoniq.axonserver.keep-alive-time
            value: "0"
          - name: axoniq.axonserver.keep-alive-timeout
            value: "604800000"
          - name: axoniq.axonserver.min-keep-alive-time
            value: "604800000"
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver-gui
  namespace: dev
spec:
  ports:
  - name: gui
    port: 8024
    targetPort: 8024
  selector:
    app: axonserver
  type: LoadBalancer
  externalIPs:
  - "192.168.20.22"
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
  namespace: dev
spec:
  ports:
  - name: grpc
    port: 8124
    targetPort: 8124
  clusterIP: 10.152.183.124
  selector:
    app: axonserver
---